import react from 'react';

const fetchCountries = async () => {
    return [
        "Algeria",
        "Andorra",
        "Angola",
        "Argentina",
        "Armenia",
        "Australia",
        "Barbados",
        "Belgium",
        "Bolivia",
        "Cameroon",
        "Canada",
        "Chile",
        "China",
        "Colombia",
        "Cuba",
        "Czech",
        "Denmark",
        "El Salvador",
        "France",
        "Iceland",
        "India",
        "Indonesia",
        "Ireland",
        "Italy",
        "Jamaica",
        "Japan",
        "Kazakhstan",
        "Kenya",
        "Lebanon",
        "Luxembourg",
        "Malaysia",
        "Mali",
        "Mexico",
        "Monaco",
        "Morocco",
        "Netherlands",
        "Nigeria",
        "Norway",
        "Palestine",
        "Paraguay",
        "Peru",
        "Philippines",
        "Portugal",
        "Qatar",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Sierra Leone",
        "Singapore",
        "Somalia",
        "South Africa",
        "South Korea",
        "Spain",
        "Sri Lanka",
        "Sudan",
        "Sweden",
        "Switzerland",
        "Syria",
        "Taiwan",
        "Thailand",
        "Tunisia",
        "Turkey",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Venezuela",
        "Vietnam",
        "Yemen"];
};

export default fetchCountries;